// SPDX-License-Identifier: Apache-2.0
// Palette adapted from BlueprintFramework/hydrodactyl resources/scripts/assets/tailwind.css.
// Adaptation: Mantine colors, light mode, and component defaults for Calagopus.
import type { CSSVariablesResolver, MantineThemeOverride } from '@mantine/core';

export const theme: MantineThemeOverride = {
  primaryColor: 'cream',
  primaryShade: { light: 7, dark: 3 },
  autoContrast: true,
  fontFamily: '"Plus Jakarta Sans", "Inter", system-ui, -apple-system, "Segoe UI", sans-serif',
  headings: { fontWeight: '600' },
  defaultRadius: 'md',
  radius: { xs: '0.375rem', sm: '0.5rem', md: '0.75rem', lg: '1rem', xl: '1.5rem' },
  colors: {
    cream: [
      '#fffdfa',
      '#fff8f0',
      '#fff5eb',
      '#fff1e0',
      '#ffedd9',
      '#f2d9bb',
      '#dec09d',
      '#85664a',
      '#5d4632',
      '#29241f',
    ],
    dark: [
      '#fff1e0',
      '#d8ccbf',
      '#b5a392',
      '#867565',
      '#433b32',
      '#29241f',
      '#1d1816',
      '#14110f',
      '#110f0d',
      '#0c0a09',
    ],
  },
  components: {
    Button: {
      defaultProps: { radius: 'md' },
      styles: { root: { fontWeight: 500, transition: 'background-color 150ms, border-color 150ms' } },
    },
    ActionIcon: { defaultProps: { radius: 'md' } },
    Card: { defaultProps: { radius: 'lg' } },
    Paper: { defaultProps: { radius: 'lg' } },
    Input: { defaultProps: { radius: 'md' } },
    Modal: { defaultProps: { radius: 'lg', overlayProps: { backgroundOpacity: 0.6, blur: 4 } } },
    Drawer: { defaultProps: { overlayProps: { backgroundOpacity: 0.6, blur: 4 } } },
    Tooltip: { defaultProps: { radius: 'sm' } },
    Menu: { defaultProps: { radius: 'md', shadow: 'lg' } },
    Tabs: { defaultProps: { variant: 'pills', radius: 'md' } },
    Badge: { defaultProps: { radius: 'xl' } },
  },
};

export const cssResolver: CSSVariablesResolver = () => ({
  variables: { '--hydro-accent': '#fa4e49' },
  dark: {
    '--mantine-color-body': '#000000',
    '--mantine-color-text': '#ffffff',
    '--mantine-color-dimmed': '#fff6eb9c',
    '--mantine-color-default': '#29241f',
    '--mantine-color-default-hover': '#433b32',
    '--mantine-color-default-border': '#ffffff11',
    '--mantine-color-anchor': '#fff1e0',
    '--hydro-surface': '#110f0d',
    '--hydro-surface-raised': '#1d1816',
    '--hydro-panel': '#ffffff08',
    '--hydro-file-row': '#1d1816',
    '--hydro-file-row-hover': '#29241f',
    '--hydro-file-selected': 'oklch(0.5108 0.1316 48.74 / 0.2)',
    '--hydro-file-selected-border': 'oklch(0.7123 0.1602 52.23 / 0.3)',
    '--hydro-file-border': '#433b3280',
    '--hydro-file-border-hover': '#5d524680',
    '--hydro-highlight': '#29241f',
    '--hydro-primary': '#fff1e0',
    '--hydro-primary-text': '#1d1816',
    '--chart-grid-color': '#fff1e012',
    '--chart-tick-color': '#b5a392',
    '--chart-series-1': '#f06f53',
  },
  light: {
    '--mantine-color-body': '#fffdfa',
    '--mantine-color-text': '#29241f',
    '--mantine-color-dimmed': '#78695a',
    '--mantine-color-default': '#fff8f0',
    '--mantine-color-default-hover': '#ffedd9',
    '--mantine-color-default-border': '#e8ddd1',
    '--mantine-color-anchor': '#85664a',
    '--hydro-surface': '#fff8f0',
    '--hydro-surface-raised': '#fffdfa',
    '--hydro-panel': '#f5f3f0',
    '--hydro-file-row': '#fffdfa',
    '--hydro-file-row-hover': '#f2eeea',
    '--hydro-file-selected': 'oklch(0.5108 0.1316 48.74 / 0.15)',
    '--hydro-file-selected-border': 'oklch(0.7123 0.1602 52.23 / 0.3)',
    '--hydro-file-border': '#29241f1a',
    '--hydro-file-border-hover': '#29241f33',
    '--hydro-highlight': '#ffedd9',
    '--hydro-primary': '#29241f',
    '--hydro-primary-text': '#fff1e0',
    '--chart-grid-color': '#29241f12',
    '--chart-tick-color': '#78695a',
    '--chart-series-1': '#c85036',
  },
});
